version: '3.8'

services:
  expense-app:
    build: .
    ports:
      - "5000-5002:3000"
    deploy:
      replicas: 3  # handle high traffic
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    restart: always
