version: '3.8'

services:
  expense-app:
    build: .
    ports:
      - "5000:3000"
    deploy:
      replicas: 3  # Ithu thaan high traffic-ah handle panna ponom
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    restart: always
